{% set version = '0.6.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-flowchart
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/flowchart_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/flowchart/flowchart_{{ version }}.tar.gz
  sha256: cbe302b46eb50bd2acf6f588d6627f87073b91f74b3106623282d612d9d18052

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-gmisc
    - r-dplyr >=1.1.0
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-gmisc
    - r-dplyr >=1.1.0
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('flowchart')"           # [not win]
    - "\"%R%\" -e \"library('flowchart')\""  # [win]

about:
  home: https://bruigtp.github.io/flowchart/
  dev_url: https://github.com/bruigtp/flowchart
  license: GPL-3.0-or-later
  summary: Creates participant flow diagrams directly from a dataframe. Representing the flow
    of participants through each stage of a study, especially in clinical trials, is
    essential to assess the generalisability and validity of the results. This package
    provides a set of functions that can be combined with a pipe operator to create
    all kinds of flowcharts from a data frame in an easy way.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - pasahe

# Package: flowchart
# Type: Package
# Title: Tidy Flowchart Generator
# Version: 0.6.0
# Authors@R: c( person("Pau", "Satorra", , "psatorra@igtp.cat", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-8144-4089")), person("Joao", "Carmezim", role = "aut", comment = c(ORCID = "0009-0009-1443-5578")), person("Natalia", "Pallares", role = "aut", comment = c(ORCID = "0000-0002-1462-379X")), person("Cristian", "Tebe", role = "aut", comment = c(ORCID = "0000-0003-2320-1385")), person("Kenneth", "Taylor", role = "ctb", comment = c(ORCID = "0000-0002-3205-9280")) )
# Maintainer: Pau Satorra <psatorra@igtp.cat>
# Description: Creates participant flow diagrams directly from a dataframe. Representing the flow of participants through each stage of a study, especially in clinical trials, is essential to assess the generalisability and validity of the results. This package provides a set of functions that can be combined with a pipe operator to create all kinds of flowcharts from a data frame in an easy way.
# License: GPL (>= 3)
# BugReports: https://github.com/bruigtp/flowchart/issues
# Encoding: UTF-8
# LazyData: true
# Imports: Gmisc, grid, tidyr, dplyr (>= 1.1.0), purrr, stringr, tibble, tidyselect, rlang, grDevices
# Suggests: knitr, ragg, rmarkdown
# VignetteBuilder: knitr
# Depends: R (>= 4.1.0)
# RoxygenNote: 7.3.2
# URL: https://bruigtp.github.io/flowchart/
# NeedsCompilation: no
# Packaged: 2024-11-08 11:31:16 UTC; psatorra
# Author: Pau Satorra [aut, cre] (<https://orcid.org/0000-0002-8144-4089>), Joao Carmezim [aut] (<https://orcid.org/0009-0009-1443-5578>), Natalia Pallares [aut] (<https://orcid.org/0000-0002-1462-379X>), Cristian Tebe [aut] (<https://orcid.org/0000-0003-2320-1385>), Kenneth Taylor [ctb] (<https://orcid.org/0000-0002-3205-9280>)
# Repository: CRAN
# Date/Publication: 2024-11-08 11:50:05 UTC
